version: "3.8"
services:
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image: wurstmeister/kafka
    environment:
      # remember to change this host address to the actual network
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    depends_on:
      kafka:
        condition: service_healthy
