{
 "title": "Kafka Monitoring",
 "description": "Kafka Resource Usage And Throughput",
 "tags": [
  "Kafka",
  "Kafka Streams",
  "Kafka Monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "broker_id",
    "label": "Broker Id",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, instance)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": { "query": "label_values(quantile)" } },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_log_log_size,topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Broker network throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\"}[5m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=\"kafka\",instance=~\"$broker_id\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"kafka\",instance=~\"$broker_id\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",instance=~\"$broker_id\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput In/Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"kafka\",instance=~\"$broker_id\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Streams Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_process_total{job=\"kafka-streams-applications\"})",
     "legendFormat": "Processed Records"
    },
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total{job=\"kafka-streams-applications\"})",
     "legendFormat": "Created Tasks"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(kafka_streams_stream_thread_metrics_process_latency_max{job=\"kafka-streams-applications\"})",
     "legendFormat": "Max Process Latency"
    },
    {
     "expr": "avg(kafka_streams_stream_thread_metrics_process_latency_avg{job=\"kafka-streams-applications\"})",
     "legendFormat": "Avg Process Latency"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_streams_stream_thread_metrics_process_rate{job=\"kafka-streams-applications\"}[20m]))",
     "legendFormat": "Process Rate"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Connections count per listener",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_count{job=\"kafka\", instance=~\"$broker_id\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections count per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_count{job=\"kafka\", instance=~\"$broker_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections creation rate per listener",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{job=\"kafka\",instance=~\"$broker_id\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections creation rate per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{job=\"kafka\",instance=~\"$broker_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections close rate per listener",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{job=\"kafka\",instance=~\"$broker_id\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connections close rate per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{job=\"kafka\",instance=~\"$broker_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Acceptor Blocked Percentage",
   "type": "graph",
   "description": "Tracks the amount of time Acceptor is blocked from accepting connections. See KIP-402 for more details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_acceptor_acceptorblockedpercent{job=\"kafka\", instance=~\"$broker_id\"}",
     "legendFormat": "{{instance}} - {{listener}}"
    }
   ]
  },
  {
   "title": "Connections per client version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_socketservermetrics_connections{job=\"kafka\",instance=~\"$broker_id\"}) by (client_software_name, client_software_version)",
     "legendFormat": "{{client_software_name}} {{client_software_version}}"
    }
   ]
  },
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Total Request Per Sec",
   "type": "stat",
   "description": "Total request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",instance=~\"$broker_id\"}[5m]))"
    }
   ]
  },
  {
   "title": "Produce Request Per Sec",
   "type": "stat",
   "description": "Produce request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\"}[5m]))"
    }
   ]
  },
  {
   "title": "Fetch Request Per Sec",
   "type": "stat",
   "description": "Fetch request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchConsumer\"}[5m]))"
    }
   ]
  },
  {
   "title": "Offset Commit Request Per Sec",
   "type": "stat",
   "description": "Offset Commit request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",instance=~\"$broker_id\",request=\"OffsetCommit\"}[5m]))"
    }
   ]
  },
  {
   "title": "Metadata Request Per Sec",
   "type": "stat",
   "description": "Metadata request rate.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{job=\"kafka\",instance=~\"$broker_id\",request=\"Metadata\"}[5m]))"
    }
   ]
  },
  {
   "title": "Produce request per sec per topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{job=\"kafka\", instance=~\"$broker_id\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch request per sec per topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{job=\"kafka\", instance=~\"$broker_id\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}